name = "cyber-defenders-dashboard"
main = "src/worker.ts"
compatibility_date = "2025-10-27"

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "DASHBOARD_CACHE"
id = "REPLACE_WITH_KV_NAMESPACE_ID_1"

[[kv_namespaces]]
binding = "STATE"
id = "REPLACE_WITH_KV_NAMESPACE_ID_2"

[vars]
USE_NEWS_API = "false"
# ADMIN_TOKEN, NEWSAPI_KEY, BING_KEY should be added as secrets:
#   wrangler secret put ADMIN_TOKEN
#   wrangler secret put NEWSAPI_KEY
#   wrangler secret put BING_KEY
