name = "cyber-defenders-dashboard"
main = "src/worker.ts"
compatibility_date = "2025-10-27"

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "DASHBOARD_CACHE"
id = "cyber-defenders-dashboard.frqkb7zyfq.workers.dev"

[[kv_namespaces]]
binding = "STATE"
id = "*-cyber-defenders-dashboard.frqkb7zyfq.workers.dev"

[vars]
USE_NEWS_API = "false"
